### ISSUE TITLE
Incomplete array jsons

### ISSUE THREAD

**Issue by wyozi** [signicode/openflights-cached#6]
This will be a bit harder to debug, since it seems to happen randomly, but I managed to replicate it (consistently) on CI and (sometimes) locally.

Basically, the JSON files generated by fetch script are incomplete. When doing `tail -n 5 node_modules/openflights-cached/dist/array.json` after installation, I get this:
```
{"airportid":"274","name":"Minna Airport","city":"Minna","country":"Nigeria","iata":"MXJ","icao":"DNMN","latitude":"9.652170181274414","longitude":"6.462259769439697","altitude":"834","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"},
{"airportid":"275","name":"Port Harcourt International Airport","city":"Port Hartcourt","country":"Nigeria","iata":"PHC","icao":"DNPO","latitude":"5.0154900550842285","longitude":"6.94959020614624","altitude":"87","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"},
{"airportid":"276","name":"Sadiq Abubakar III International Airport","city":"Sokoto","country":"Nigeria","iata":"SKO","icao":"DNSO","latitude":"12.916299819946289","longitude":"5.207190036773682","altitude":"1010","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"},
{"airportid":"277","name":"Yola Airport","city":"Yola","country":"Nigeria","iata":"YOL","icao":"DNYO","latitude":"9.257550239562988","longitude":"12.430399894714355","altitude":"599","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"},
{"airportid":"278","name":"Zaria Airport","city":"Zaria","country":"Nigeria","iata":"ZAR","icao":"DNZA","latitude":"11.1302","longitude":"7.68581","altitude":"2170","timezone":"1","dst":"N","tz":"Africa/Lagos","type":"airport","source":"OurAirports"}
```

The JSON array ending and rest of the airports are completely missing. Running it again returns the same results from `tail`. 

It might be just a transient error, but I wanted to put it here in case someone else has it.

**Comment by MichalCz** [comment]
Yeah - sometimes download fails. I noticed that in a couple builds, although it should be captured and the download should repeat...

**Comment by MichalCz** [comment]
Will look into that shortly.

**Comment by wyozi** [comment]
Since we still get some data, I think the HTTP status code is 200. Therefore it seems that the stream just doesn't receive all the chunks and the fetch script terminates immaturely.

One guess I have is that the node process is terminated before completion, since all logic is happening within a Promise (that might even get garbage collected).

**Comment by MichalCz** [comment]
Well that actually should not happen. It's a stream and it gets completed -
the question is if just without an ending bracket or is that couple lines.

Notice that it's always a full line, so that's curious.

>

**Comment by MichalCz** [comment]
Yeah - seems that this happens in Travis, but not for me locally. There may be some kind of `fs` race condition. I'll try to simulate that.
